/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

void onSurfaceCreated();

void onSurfaceChanged();

void onDrawFrame();

/* Header for class com_example_viewsharp_pacman_RendererWrapper */

#ifndef _Included_com_example_viewsharp_pacman_RendererWrapper
#define _Included_com_example_viewsharp_pacman_RendererWrapper
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_example_viewsharp_pacman_RendererWrapper
 * Method:    onSurfaceCreated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_viewsharp_pacman_RendererWrapper_onSurfaceCreatedJNI
        (JNIEnv *env, jobject obj) {
    onSurfaceCreated();
}

/*
 * Class:     com_example_viewsharp_pacman_RendererWrapper
 * Method:    onSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_viewsharp_pacman_RendererWrapper_onSurfaceChangedJNI
        (JNIEnv *, jobject, jint, jint) {
    onSurfaceChanged();
}

/*
 * Class:     com_example_viewsharp_pacman_RendererWrapper
 * Method:    onDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_viewsharp_pacman_RendererWrapper_onDrawFrameJNI
        (JNIEnv *, jobject) {
    onDrawFrame();
}

#ifdef __cplusplus
}
#endif
#endif