/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/asset_manager_jni.h>

#include "macros.h"

/* Header for class com_example_viewsharp_pacman_RendererWrapper */

#ifndef _Included_com_example_viewsharp_pacman_RendererWrapper
#define _Included_com_example_viewsharp_pacman_RendererWrapper

void onSurfaceCreated();

void onSurfaceChanged(int width, int height);

void onDrawFrame();

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_example_viewsharp_pacman_RendererWrapper
 * Method:    onSurfaceCreated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_viewsharp_pacman_RendererWrapper_onSurfaceCreatedJNI
        (JNIEnv *, jobject) {
    onSurfaceCreated();
}

/*
 * Class:     com_example_viewsharp_pacman_RendererWrapper
 * Method:    onSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_viewsharp_pacman_RendererWrapper_onSurfaceChangedJNI
        (JNIEnv *, jobject, jint width, jint height) {
    onSurfaceChanged((int)width, (int)height);
}

/*
 * Class:     com_example_viewsharp_pacman_RendererWrapper
 * Method:    onDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_viewsharp_pacman_RendererWrapper_onDrawFrameJNI
        (JNIEnv *, jobject) {
    onDrawFrame();
}

#ifdef __cplusplus
}
#endif
#endif