/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

void onSurfaceCreated();

void onSurfaceChanged();

void onDrawFrame();

/* Header for class com_example_viewsharp_pacman_RendererWrapper */

#ifndef _Included_com_example_viewsharp_pacman_RendererWrapper
#define _Included_com_example_viewsharp_pacman_RendererWrapper
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_example_viewsharp_pacman_RendererWrapper
 * Method:    onSurfaceCreated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_viewsharp_pacman_RendererWrapper_onSurfaceCreated
        (JNIEnv *env, jobject obj) {
    onSurfaceCreated();



//    jclass RendererWrapper = env->FindClass("com/example/viewsharp/pacman/RendererWrapper");
//    if (RendererWrapper) {
//        jmethodID qvt = env->GetStaticMethodID(RendererWrapper, "qvt", "(I)I");
//        jint result = env->CallIntMethod(RendererWrapper, qvt, (jint) 5);
//    }
}

/*
 * Class:     com_example_viewsharp_pacman_RendererWrapper
 * Method:    onSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_viewsharp_pacman_RendererWrapper_onSurfaceChanged
        (JNIEnv *, jobject, jint, jint) {
    onSurfaceChanged();
}

/*
 * Class:     com_example_viewsharp_pacman_RendererWrapper
 * Method:    onDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_viewsharp_pacman_RendererWrapper_onDrawFrame
        (JNIEnv *, jobject) {
    onDrawFrame();
}

#ifdef __cplusplus
}
#endif
#endif