/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "game.h"
/* Header for class com_example_viewsharp_pacman_GameLibJNIWrapper */

#ifndef _Included_com_example_viewsharp_pacman_GameLibJNIWrapper
#define _Included_com_example_viewsharp_pacman_GameLibJNIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_viewsharp_pacman_GameLibJNIWrapper
 * Method:    on_surface_created
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_viewsharp_pacman_GameLibJNIWrapper_on_1surface_1created
  (JNIEnv *, jclass) {
    on_surface_created();
}

/*
 * Class:     com_example_viewsharp_pacman_GameLibJNIWrapper
 * Method:    on_surface_changed
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_viewsharp_pacman_GameLibJNIWrapper_on_1surface_1changed
  (JNIEnv *, jclass, jint, jint){
    on_surface_changed();
}

/*
 * Class:     com_example_viewsharp_pacman_GameLibJNIWrapper
 * Method:    on_draw_frame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_viewsharp_pacman_GameLibJNIWrapper_on_1draw_1frame
  (JNIEnv *, jclass){
    on_draw_frame();
}

#ifdef __cplusplus
}
#endif
#endif
